site_name: NoteWorthy Documentation
site_url: https://example.com/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - navigation.expand

nav:
  - Home: 'index.md'
  - Getting Started:
    - Frontend Setup: 'getting-started/frontendsetup.md'
    - Backend Setup: 'getting-started/backendsetup.md'

plugins:
  - search
  - git-revision-date

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/chownces/NoteWorthy
      name: GitHub

repo_url: https://github.com/chownces/NoteWorthy
repo_name: NoteWorthy

copyright: Copyright &copy; 2021 NoteWorthy