site_name: NoteWorthy Documentation
site_url: https://chownces.github.io/NoteWorthy-Documentation/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - navigation.expand

nav:
  - Home: 'index.md'
  - Project Overview:
    - Problem Motivation & Core Features: 'project-overview/problemmotivation.md'
    - Poster and Video: 'project-overview/postervideo.md'
    - Project Timeline: 'project-overview/timeline.md'
    - Implementation Details: 
      - Tech Stack: 'project-overview/implementationdetails/techstack.md'
      - Why this tech stack?:  'project-overview/implementationdetails/whytechstack.md'
      - Deployment: 'project-overview/implementationdetails/deployment.md'
      - CI/CD & Workflow: 'project-overview/implementationdetails/workflow.md'
    - Learning Points: 'project-overview/learningpoints.md'
    - Project Log: 'project-overview/projectlog.md'
  - Developer Guide:
    - Getting Started:
      - Frontend Setup: 'getting-started/frontendsetup.md'
      - Backend Setup: 'getting-started/backendsetup.md'

plugins:
  - search
  - git-revision-date

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/chownces/NoteWorthy
      name: GitHub

copyright: Copyright &copy; 2021 NoteWorthy